name: 'Build customwcs-electron'
description: 'Runs predefined command that compiles wcs-electron package for os and provides output with result file name'
author: 'Core3'
inputs:
  packageFolder: 
    required: true
    description: 'Path to folder with package to build'
    default: './'
  feature: 
    required: false
    description: 'name of the feature'
    default: ''
  featureConfig: 
    required: false
    description: 'config file for feature'
    default: ''
  publish: 
    required: false
    description: 'publish parameter. One of( "onTag", "onTagOrDraft", "always", "never"). Default is "always"'
    default: 'always'
  buildCmd: 
    required: true
    description: 'build command to execute to compile install package'
    default: 'yarn build:wcs'
  buildFolder: 
    required: false
    description: 'path relative to packageFolder where result files will be'
    default: 'build'
  macCerts: 
    required: false
    description: 'mac OS siging certificate'
    default: ''
  macCertsPassword: 
    required: false
    description: 'mac OS siging certificate password'
    default: ''
  windowsCerts: 
    required: false
    description: 'win OS siging certificate'
    default: ''
  windowsCertsPassword: 
    required: false
    description: 'win OS siging certificate password'
    default: ''
outputs:
  packageFile: # id of the output
    description: 'Name of the compiled installation package'
  packageFile2: # id of the output
    description: 'Name of the secondary compiled installation package'
runs:
  using: 'node12'
  main: 'dist/index.js'

 